export const PLAY_SONG = 'PLAY_SONG'
export const STOP_SONG = 'STOP_SONG'
export const ADD_SONG = 'ADD_SONG'
export const RECEIVE_SONGS = 'RECEIVE_SONGS'
export const RECEIVE_ALL = 'RECEIVE_ALL'
export const GET_MEDIA_SOURCE = 'GET_MEDIA_SOURCE'
export const SET_MEDIA_SOURCE = 'SET_MEDIA_SOURCE'
